name: API Validation

on:
  push:
    branches:
      - main

jobs:
  validate-manifest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v2

      - name: Use Node.js 14.x
        uses: actions/setup-node@v2
        with:
          node-version: 14.x

      - name: Install dependencies
        run: npm install --global insomnia-inso

      - name: Lint OpenAPI
        run: inso lint spec apis/bets-api.yaml

      - name: Print OpenAPI
        run: cat apis/bets-api.yaml