name: Manifest Generation

on:
  push:
    branches:
      - main

jobs:
  generate-manifest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v2

      - name: Use Node.js 14.x
        uses: actions/setup-node@v2
        with:
          node-version: 14.x

      - name: Install dependencies
        run: npm install --global insomnia-inso

      - name: Generate K8s Manifest
        run: inso generate config apis/bets-api.yaml --type kubernetes --output bets-api-manifest.yaml

      - name: Print Manifest
        run: cat bets-api-manifest.yaml